# Generated by Django 5.2.7 on 2025-12-17 09:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_account', '0003_alter_gameaccount_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvenesLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cardPoolType', models.CharField(max_length=255, verbose_name='Card Pool Type')),
                ('resourceId', models.BigIntegerField(verbose_name='Resource ID')),
                ('qualityLevel', models.IntegerField(verbose_name='Quality Level')),
                ('resourceType', models.CharField(max_length=50, verbose_name='Resource Type')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('count', models.IntegerField(verbose_name='Count')),
                ('time', models.DateTimeField(verbose_name='Time')),
                ('game_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_account.gameaccount')),
            ],
            options={
                'verbose_name': 'Convene Log',
                'verbose_name_plural': 'Convene Logs',
                'ordering': ['-time'],
            },
        ),
    ]
