# Generated by Django 5.2.7 on 2025-12-15 06:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('oauth_code', models.CharField(max_length=40, null=True, verbose_name='OAuth Code')),
                ('uid', models.CharField(max_length=10, verbose_name='UID')),
            ],
        ),
    ]
