# Generated by Django 5.2.7 on 2025-12-15 07:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_account', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameaccount',
            options={'verbose_name': 'GameAcocunt', 'verbose_name_plural': 'GameAccounts'},
        ),
        migrations.AddConstraint(
            model_name='gameaccount',
            constraint=models.UniqueConstraint(fields=('user', 'uid'), name='unique_user_uid'),
        ),
    ]
